name: plugfox_badges_faas
description: Plugfox badges on Google Cloud Run
version: 0.0.1-dev
# homepage: https://www.example.com
publish_to: 'none'

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  meta: ^1.2.4
  http: ^0.13.3
  functions_framework: ^0.4.1
  shelf: ^1.1.4
  image: ^3.0.2
  #gcloud: ^0.7.3

dev_dependencies:
  build_runner: ^2.0.4
  build_verify: ^2.0.0
  functions_framework_builder: ^0.4.2
  test: ^1.15.7
  mockito: ^5.0.9
  test_process: ^2.0.0
  pedantic: ^1.9.2
